apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music
  creationTimestamp: null
  name: spring-music.apps.local.20241004.1057.29585
spec:
  refName: spring-music.apps.local
  releasedAt: "2024-10-04T11:01:44Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: quay.io/vdesikanvmware/springmusic@sha256:c55871bef18e4832d0e4ca2850df7416ccaea79000ab357cbbd18d4eafd7d379
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20241004.1057.29585
