---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: spring-music-config
  annotations:
    apps.tanzu.vmware.com/promotable: ""
spec:
  routes:
  - predicates:
    - Path=/**,/albums/**
    - Method=GET,POST,DELETE
    order: 1000
    filters:
    - StripPrefix=0
  service:
    name: spring-music
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: spring-music-mapping
  annotations:
    apps.tanzu.vmware.com/promotable: ""
spec:
  gatewayRef:
    name: spring-cloud-gateway
  routeConfigRef:
    name: spring-music-config
